### ISSUE TITLE
Unexpected exception: FileNotFoundException legui.json

### ISSUE THREAD

**Issue by KeyJ148** [SpinyOwl/legui#135]
I find it strange that an error is written to the log when I simply use the library.
Or do I have to fill in file legui.json with something?
```
java.io.FileNotFoundException: legui.json
	at org.liquidengine.legui.util.IOUtil.resourceToByteBuffer(IOUtil.java:46)
	at org.liquidengine.legui.util.IOUtil.resourceToString(IOUtil.java:98)
	at org.liquidengine.legui.config.Configuration.getJson(Configuration.java:61)
	at org.liquidengine.legui.config.Configuration.initialize(Configuration.java:44)
	at org.liquidengine.legui.config.Configuration.<clinit>(Configuration.java:19)
	at org.liquidengine.legui.system.context.Context.<clinit>(Context.java:22)
	at org.liquidengine.legui.DefaultInitializer.<init>(DefaultInitializer.java:33)
```
Version: 3.3.5

**Comment by SpinyOwl** [comment]
Sorry for so late reply, just realized that I have more open issues than before 😰 

This was made by intention, however it was more bug rather than feature.

This issue was fixed in `4.1.0`  
The latest version is `4.2.0`

Hope that helps.
