### ISSUE TITLE
java.lang.NoSuchMethodError: 'void org.lwjgl.system.ThreadLocalUtil.setFunctionMissingAddresses(int, int)'

### ISSUE THREAD

**Issue by nextdayy** [SpinyOwl/legui#136]
Hi, I tried to build legui for contribution to it and research into playing video, but when I tried to run this on Java 16 I got this error upon starting:

```
Exception in thread "main" java.lang.NoSuchMethodError: 'void org.lwjgl.system.ThreadLocalUtil.setFunctionMissingAddresses(int, int)'
	at org.lwjgl.opengl.GL.create(GL.java:183)
	at org.lwjgl.opengl.GL.create(GL.java:129)
	at org.lwjgl.opengl.GL.create(GL.java:115)
	at org.lwjgl.opengl.GL.<clinit>(GL.java:85)
```
	
Not sure if this is something I'm doing wrong, also the CONTRIBUTING.md no longer exists so I couldn't check that either.
Thanks for your help!

**Comment by SpinyOwl** [comment]
Foremost, sorry for the late reply.

This kind of issue looks like you have different version of LWJGL then the one specified in the gradle properties.
Could you please check it?
